export const ADDRESSES_LIST = 'ADDRESSES_LIST';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const GET_ONE_ADDRESS = 'GET_ONE_ADDRESS';
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';
export const MULTIPLE_ADDRESSES = 'MULTIPLE_ADDRESSES';
