export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const GET_CARTS = 'GET_CARTS';
export const CART_UPDATE_FULLFILLED_STATE = 'CART_UPDATE_FULLFILLED_STATE';
