export const INIT_APP_ACTION_TYPE = 'INIT_APP_ACTION_TYPE';
export const SET_AUTH_FROM_STORAGE = 'SET_AUTH_FROM_STORAGE';
export const CATEGORIES_TREE_REQUEST = 'CATEGORIES_TREE_REQUEST';
export const SWITCH_LOCALE = 'SWITCH_LOCALE';
export const IS_PAGE_LOCKED = 'IS_PAGE_LOCKED';
export const ANONYM_ID = 'ANONYM_ID';
